on: [push]
name: CI
jobs:
  cabal:
    name: Cabal / GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
        - "8.10.7"
        - "9.0.2"
        - "9.2.8"
        - "9.4.5"
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.8.1.0'
    - run: cabal build all --enable-tests
    - run: cabal test all

  stack:
    name: Stack / GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ghc: "8.10.7"
          yaml: "stack-8.10.7.yaml"
        - ghc: "9.0.2 (aeson-1)"
          yaml: "stack-9.0.2-aeson1.yaml"
        - ghc: "9.0.2 (aeson-2)"
          yaml: "stack-9.0.2-aeson2.yaml"
        - ghc: "9.2.8"
          yaml: "stack-9.2.8.yaml"
        - ghc: "9.4.5"
          yaml: "stack.yaml"
    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: "latest"

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.yaml }}-stack2

    - name: Build
      run: |
        stack build --stack-yaml ${{matrix.yaml}} --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --stack-yaml ${{matrix.yaml}} --system-ghc
